/*
 * ApplicationConfig.java
 *
 * Generated on 24.9.2021 14:50
 *
 */

package org.netbeans.rest.application.config;

import java.util.Set;
import javax.ws.rs.core.Application;

/**
 *
 * @author Franky Laseure
 */
@javax.ws.rs.ApplicationPath("webresources")
public class ApplicationConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        return getRestResourceClasses();
    }

    /**
     * Do not modify this method. It is automatically generated by NetBeans REST support.
     */
    private Set<Class<?>> getRestResourceClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
//Custom code, do not change this line
//add here custom operations
//Custom code, do not change this line   
        resources.add(film.restservices.RSPhotoDataError.class);
        resources.add(film.restservices.arealevel1.RSArealevel1_delete.class);
        resources.add(film.restservices.arealevel1.RSArealevel1_insert.class);
        resources.add(film.restservices.arealevel1.RSArealevel1_select.class);
        resources.add(film.restservices.arealevel1.RSArealevel1_update.class);
        resources.add(film.restservices.arealevel2.RSArealevel2_delete.class);
        resources.add(film.restservices.arealevel2.RSArealevel2_insert.class);
        resources.add(film.restservices.arealevel2.RSArealevel2_select.class);
        resources.add(film.restservices.arealevel2.RSArealevel2_update.class);
        resources.add(film.restservices.arealevel3.RSArealevel3_delete.class);
        resources.add(film.restservices.arealevel3.RSArealevel3_insert.class);
        resources.add(film.restservices.arealevel3.RSArealevel3_select.class);
        resources.add(film.restservices.arealevel3.RSArealevel3_update.class);
        resources.add(film.restservices.art_academy.RSArt_academy_delete.class);
        resources.add(film.restservices.art_academy.RSArt_academy_insert.class);
        resources.add(film.restservices.art_academy.RSArt_academy_select.class);
        resources.add(film.restservices.art_academy.RSArt_academy_update.class);
        resources.add(film.restservices.art_group.RSArt_group_delete.class);
        resources.add(film.restservices.art_group.RSArt_group_insert.class);
        resources.add(film.restservices.art_group.RSArt_group_select.class);
        resources.add(film.restservices.art_group.RSArt_group_update.class);
        resources.add(film.restservices.art_photo.RSArt_photo_delete.class);
        resources.add(film.restservices.art_photo.RSArt_photo_insert.class);
        resources.add(film.restservices.art_photo.RSArt_photo_select.class);
        resources.add(film.restservices.art_photo.RSArt_photo_update.class);
        resources.add(film.restservices.art_subgroup.RSArt_subgroup_delete.class);
        resources.add(film.restservices.art_subgroup.RSArt_subgroup_insert.class);
        resources.add(film.restservices.art_subgroup.RSArt_subgroup_select.class);
        resources.add(film.restservices.art_subgroup.RSArt_subgroup_update.class);
        resources.add(film.restservices.country.RSCountry_delete.class);
        resources.add(film.restservices.country.RSCountry_insert.class);
        resources.add(film.restservices.country.RSCountry_select.class);
        resources.add(film.restservices.country.RSCountry_update.class);
        resources.add(film.restservices.creator.RSCreator_delete.class);
        resources.add(film.restservices.creator.RSCreator_insert.class);
        resources.add(film.restservices.creator.RSCreator_select.class);
        resources.add(film.restservices.creator.RSCreator_update.class);
        resources.add(film.restservices.film.RSFilm_delete.class);
        resources.add(film.restservices.film.RSFilm_insert.class);
        resources.add(film.restservices.film.RSFilm_select.class);
        resources.add(film.restservices.film.RSFilm_update.class);
        resources.add(film.restservices.filmsubjects.RSFilmsubjects_delete.class);
        resources.add(film.restservices.filmsubjects.RSFilmsubjects_insert.class);
        resources.add(film.restservices.filmsubjects.RSFilmsubjects_select.class);
        resources.add(film.restservices.filmsubjects.RSFilmsubjects_update.class);
        resources.add(film.restservices.filmtype.RSFilmtype_delete.class);
        resources.add(film.restservices.filmtype.RSFilmtype_insert.class);
        resources.add(film.restservices.filmtype.RSFilmtype_select.class);
        resources.add(film.restservices.filmtype.RSFilmtype_update.class);
        resources.add(film.restservices.geography_columns.RSGeography_columns_select.class);
        resources.add(film.restservices.geometry_columns.RSGeometry_columns_select.class);
        resources.add(film.restservices.locality.RSLocality_delete.class);
        resources.add(film.restservices.locality.RSLocality_insert.class);
        resources.add(film.restservices.locality.RSLocality_select.class);
        resources.add(film.restservices.locality.RSLocality_update.class);
        resources.add(film.restservices.mainmenu.RSMainmenu_delete.class);
        resources.add(film.restservices.mainmenu.RSMainmenu_insert.class);
        resources.add(film.restservices.mainmenu.RSMainmenu_select.class);
        resources.add(film.restservices.mainmenu.RSMainmenu_update.class);
        resources.add(film.restservices.menu.RSMenu_delete.class);
        resources.add(film.restservices.menu.RSMenu_insert.class);
        resources.add(film.restservices.menu.RSMenu_select.class);
        resources.add(film.restservices.menu.RSMenu_update.class);
        resources.add(film.restservices.menuitem.RSMenuitem_delete.class);
        resources.add(film.restservices.menuitem.RSMenuitem_insert.class);
        resources.add(film.restservices.menuitem.RSMenuitem_select.class);
        resources.add(film.restservices.menuitem.RSMenuitem_update.class);
        resources.add(film.restservices.photo.RSPhoto_delete.class);
        resources.add(film.restservices.photo.RSPhoto_insert.class);
        resources.add(film.restservices.photo.RSPhoto_select.class);
        resources.add(film.restservices.photo.RSPhoto_update.class);
        resources.add(film.restservices.photosubjects.RSPhotosubjects_delete.class);
        resources.add(film.restservices.photosubjects.RSPhotosubjects_insert.class);
        resources.add(film.restservices.photosubjects.RSPhotosubjects_select.class);
        resources.add(film.restservices.photosubjects.RSPhotosubjects_update.class);
        resources.add(film.restservices.phototags.RSPhototags_delete.class);
        resources.add(film.restservices.phototags.RSPhototags_insert.class);
        resources.add(film.restservices.phototags.RSPhototags_select.class);
        resources.add(film.restservices.phototags.RSPhototags_update.class);
        resources.add(film.restservices.phototree7subject.RSPhototree7subject_delete.class);
        resources.add(film.restservices.phototree7subject.RSPhototree7subject_insert.class);
        resources.add(film.restservices.phototree7subject.RSPhototree7subject_select.class);
        resources.add(film.restservices.phototree7subject.RSPhototree7subject_update.class);
        resources.add(film.restservices.postalcode.RSPostalcode_delete.class);
        resources.add(film.restservices.postalcode.RSPostalcode_insert.class);
        resources.add(film.restservices.postalcode.RSPostalcode_select.class);
        resources.add(film.restservices.postalcode.RSPostalcode_update.class);
        resources.add(film.restservices.raster_columns.RSRaster_columns_select.class);
        resources.add(film.restservices.raster_overviews.RSRaster_overviews_select.class);
        resources.add(film.restservices.route.RSRoute_delete.class);
        resources.add(film.restservices.route.RSRoute_insert.class);
        resources.add(film.restservices.route.RSRoute_select.class);
        resources.add(film.restservices.route.RSRoute_update.class);
        resources.add(film.restservices.securityprofile.RSSecurityprofile_delete.class);
        resources.add(film.restservices.securityprofile.RSSecurityprofile_insert.class);
        resources.add(film.restservices.securityprofile.RSSecurityprofile_select.class);
        resources.add(film.restservices.securityprofile.RSSecurityprofile_update.class);
        resources.add(film.restservices.securityuserprofile.RSSecurityuserprofile_delete.class);
        resources.add(film.restservices.securityuserprofile.RSSecurityuserprofile_insert.class);
        resources.add(film.restservices.securityuserprofile.RSSecurityuserprofile_select.class);
        resources.add(film.restservices.securityuserprofile.RSSecurityuserprofile_update.class);
        resources.add(film.restservices.spatial_ref_sys.RSSpatial_ref_sys_delete.class);
        resources.add(film.restservices.spatial_ref_sys.RSSpatial_ref_sys_insert.class);
        resources.add(film.restservices.spatial_ref_sys.RSSpatial_ref_sys_select.class);
        resources.add(film.restservices.spatial_ref_sys.RSSpatial_ref_sys_update.class);
        resources.add(film.restservices.subject.RSSubject_delete.class);
        resources.add(film.restservices.subject.RSSubject_insert.class);
        resources.add(film.restservices.subject.RSSubject_select.class);
        resources.add(film.restservices.subject.RSSubject_update.class);
        resources.add(film.restservices.subjectcat.RSSubjectcat_delete.class);
        resources.add(film.restservices.subjectcat.RSSubjectcat_insert.class);
        resources.add(film.restservices.subjectcat.RSSubjectcat_select.class);
        resources.add(film.restservices.subjectcat.RSSubjectcat_update.class);
        resources.add(film.restservices.sublocality.RSSublocality_delete.class);
        resources.add(film.restservices.sublocality.RSSublocality_insert.class);
        resources.add(film.restservices.sublocality.RSSublocality_select.class);
        resources.add(film.restservices.sublocality.RSSublocality_update.class);
        resources.add(film.restservices.tree7subject.RSTree7subject_delete.class);
        resources.add(film.restservices.tree7subject.RSTree7subject_insert.class);
        resources.add(film.restservices.tree7subject.RSTree7subject_select.class);
        resources.add(film.restservices.tree7subject.RSTree7subject_update.class);
        resources.add(film.restservices.uploadsession.RSUploadsession_delete.class);
        resources.add(film.restservices.uploadsession.RSUploadsession_insert.class);
        resources.add(film.restservices.uploadsession.RSUploadsession_select.class);
        resources.add(film.restservices.uploadsession.RSUploadsession_update.class);
        resources.add(film.restservices.uploadsessionsettings.RSUploadsessionsettings_delete.class);
        resources.add(film.restservices.uploadsessionsettings.RSUploadsessionsettings_insert.class);
        resources.add(film.restservices.uploadsessionsettings.RSUploadsessionsettings_select.class);
        resources.add(film.restservices.uploadsessionsettings.RSUploadsessionsettings_update.class);
        resources.add(film.restservices.view_backupstatus.RSView_backupstatus_select.class);
        resources.add(film.restservices.view_countryphotocount.RSView_countryphotocount_select.class);
        resources.add(film.restservices.view_locality_photolocations.RSView_locality_photolocations_select.class);
        resources.add(film.restservices.view_localityphotocount.RSView_localityphotocount_select.class);
        resources.add(film.restservices.view_locationtree.RSView_locationtree_select.class);
        resources.add(film.restservices.view_photo_firstlastdate.RSView_photo_firstlastdate_select.class);
        resources.add(film.restservices.view_photodates.RSView_photodates_select.class);
        resources.add(film.restservices.view_photodatespublic.RSView_photodatespublic_select.class);
        resources.add(film.restservices.view_photolocations.RSView_photolocations_select.class);
        resources.add(film.restservices.view_publiccountryphotocount.RSView_publiccountryphotocount_select.class);
        resources.add(film.restservices.view_publiclocalityphotocount.RSView_publiclocalityphotocount_select.class);
        resources.add(film.restservices.view_publicphotolocations.RSView_publicphotolocations_select.class);
        resources.add(film.restservices.view_subjects_for_film.RSView_subjects_for_film_select.class);
        resources.add(film.restservices.view_subjects_for_photo.RSView_subjects_for_photo_select.class);
        return resources;
    }
}
//needs customization by programmer ?
